#!/usr/bin/env node
/**
 * Design token build.
 *
 *   npm run tokens          build once
 *   npm run tokens:check    fail if the generated files are out of date (CI runs this)
 *   npm run tokens:watch    rebuild whenever tokens/tokens.json changes
 *
 * Input:   tokens/tokens.json        W3C Design Tokens (DTCG) format
 * Outputs: assets/css/tokens.css     CSS custom properties on :root (used by every page)
 *          assets/data/tokens.json   flat, resolved list (used by the design system page)
 *
 * Naming: the token path joined with "-" and prefixed with "--". A segment
 * named "default" is dropped, so color.text.default becomes --color-text.
 *
 * Shadows (DTCG composite, one layer or a list) become box-shadow values and
 * cubicBezier arrays become cubic-bezier().
 *
 * Aliases such as "{color.accent.default}" are written as var(--color-accent),
 * so changing the accent flows through every token that points at it.
 *
 * No dependencies. Needs Node 18 or newer.
 */
import { readFileSync, writeFileSync, mkdirSync, watch } from "node:fs";
import { dirname, resolve, relative } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = resolve(root, "tokens/tokens.json");
const OUT_CSS = resolve(root, "assets/css/tokens.css");
const OUT_JSON = resolve(root, "assets/data/tokens.json");

const cssName = (path) => "--" + path.filter((p) => p !== "default").join("-");

/** Walk the DTCG tree. Groups pass their $type down to their tokens. */
function collect(node, path = [], inheritedType, out = []) {
  for (const [key, val] of Object.entries(node)) {
    if (key.startsWith("$") || val === null || typeof val !== "object" || Array.isArray(val)) continue;
    const type = val.$type ?? inheritedType;
    if ("$value" in val) out.push({ path: [...path, key], type, value: val.$value, description: val.$description ?? "" });
    else collect(val, [...path, key], type, out);
  }
  return out;
}

function formatValue(type, value) {
  if (type === "fontFamily") {
    return (Array.isArray(value) ? value : [value]).map((f) => (/\s/.test(f) ? `"${f}"` : f)).join(", ");
  }
  // DTCG shadow: one object or a list of layers → CSS box-shadow
  if (type === "shadow" && typeof value === "object") {
    return (Array.isArray(value) ? value : [value])
      .map((s) => [s.inset ? "inset" : "", s.offsetX ?? "0px", s.offsetY ?? "0px", s.blur ?? "0px", s.spread ?? "0px", s.color].filter(Boolean).join(" "))
      .join(", ");
  }
  // DTCG cubicBezier: [x1, y1, x2, y2] → cubic-bezier()
  if (type === "cubicBezier" && Array.isArray(value)) return `cubic-bezier(${value.join(", ")})`;
  return String(value);
}

function build() {
  const tokens = collect(JSON.parse(readFileSync(SRC, "utf8")));
  const byPath = new Map(tokens.map((t) => [t.path.join("."), t]));
  const lookup = (ref) => byPath.get(ref) ?? byPath.get(`${ref}.default`);
  const errors = [];

  // Validate names and types
  const seen = new Map();
  for (const t of tokens) {
    const id = t.path.join(".");
    t.name = cssName(t.path);
    if (seen.has(t.name)) errors.push(`${id} and ${seen.get(t.name)} would both become ${t.name}`);
    seen.set(t.name, id);
    if (!t.type) errors.push(`${id} has no $type. Set it on the token or on a parent group.`);
  }

  // Resolve aliases: CSS keeps var() references, the JSON gets the final value
  const resolveToken = (t, depth = 0) => {
    const isAlias = typeof t.value === "string" && /^\{[^}]+\}$/.test(t.value);
    if (!isAlias) return { css: formatValue(t.type, t.value), value: formatValue(t.type, t.value), alias: null };
    const target = lookup(t.value.slice(1, -1));
    if (!target) { errors.push(`${t.path.join(".")} points at ${t.value}, which doesn't exist`); return { css: "", value: "", alias: null }; }
    if (depth > 8) { errors.push(`${t.path.join(".")} is part of a circular alias`); return { css: "", value: "", alias: null }; }
    return { css: `var(${cssName(target.path)})`, value: resolveToken(target, depth + 1).value, alias: target.path.join(".") };
  };
  for (const t of tokens) Object.assign(t, resolveToken(t));

  if (errors.length) {
    console.error("Token errors:\n  " + errors.join("\n  "));
    process.exit(1);
  }

  // CSS, grouped under comments
  const groupOf = (t) => t.path.slice(0, ["color", "font"].includes(t.path[0]) ? 2 : 1).join(".");
  let css = "/* Generated by scripts/build-tokens.mjs from tokens/tokens.json.\n   Don't edit by hand: change tokens/tokens.json and run `npm run tokens`. */\n\n:root {\n  color-scheme: dark;\n";
  let group = null;
  for (const t of tokens) {
    if (groupOf(t) !== group) { group = groupOf(t); css += `\n  /* ${group} */\n`; }
    const note = t.description ? ` /* ${t.description.replace(/\*\//g, "")} */` : "";
    css += `  ${t.name}: ${t.css};${note}\n`;
  }
  css += "}\n";

  const data = JSON.stringify({
    generated_from: "tokens/tokens.json",
    count: tokens.length,
    tokens: tokens.map((t) => ({ path: t.path.join("."), name: t.name, type: t.type, value: t.value, css: t.css, alias: t.alias, description: t.description })),
  }, null, 2) + "\n";

  return { css, data, count: tokens.length };
}

function run(mode) {
  const { css, data, count } = build();
  const outputs = [[OUT_CSS, css], [OUT_JSON, data]];
  if (mode === "--check") {
    const stale = outputs.filter(([file, want]) => { try { return readFileSync(file, "utf8") !== want; } catch { return true; } });
    if (stale.length) {
      console.error(`Out of date: ${stale.map(([f]) => relative(root, f)).join(", ")}. Run \`npm run tokens\` and commit the result.`);
      process.exit(1);
    }
    console.log(`Tokens up to date (${count} tokens).`);
    return;
  }
  for (const [file, content] of outputs) { mkdirSync(dirname(file), { recursive: true }); writeFileSync(file, content); }
  console.log(`Built ${count} tokens → ${outputs.map(([f]) => relative(root, f)).join(", ")}`);
}

const mode = process.argv[2];
run(mode);
if (mode === "--watch") {
  console.log("Watching tokens/tokens.json. Press Ctrl+C to stop.");
  let timer;
  watch(SRC, () => {
    clearTimeout(timer);
    timer = setTimeout(() => { try { run(); } catch (e) { console.error(e.message); } }, 100);
  });
}
